/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'edwin' at '10/25/16 2:48 PM' with Gradle 2.14.1
 *
 * @author edwin, @date 10/25/16 2:48 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
